version: '3.9'

services:
#  web.api:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_HTTP_PORTS=8080
#      - ASPNETCORE_HTTPS_PORTS=8081
#    ports:
#      - "8080"
#      - "8081"
#    volumes:
#      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
#      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

#  mongo:
#    image: mongo:latest
#    container_name: MongoDb
#    ports:
#      - "27018:27017"
#    restart: "always"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=Aa123456789*-+
#    network_mode: bridge

#  mongo1:
#    image: mongo
#    container_name: mongo1
#    restart: always
#    ports:
#      - "27017:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=Aa123456789*-+
#    command: mongod --replSet rs0
#
#  mongo2:
#    image: mongo
#    container_name: mongo2
#    restart: always
#    ports:
#      - "27018:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=Aa123456789*-+
#    command: mongod --replSet rs0
#
#  mongo3:
#    image: mongo
#    container_name: mongo3
#    restart: always
#    ports:
#      - "27019:27017"
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=admin
#      - MONGO_INITDB_ROOT_PASSWORD=Aa123456789*-+
#    command: mongod --replSet rs0
#
#networks:
#  default:
#    driver: bridge



 Shard cluster
version: '3.7'

services:
  configsvr1:
    image: mongo:latest
    container_name: configsvr1
    command: mongod --configsvr --replSet configrs --port 27017
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - mongo-cluster

  configsvr2:
    image: mongo:latest
    container_name: configsvr2
    command: mongod --configsvr --replSet configrs --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - mongo-cluster

  configsvr3:
    image: mongo:latest
    container_name: configsvr3
    command: mongod --configsvr --replSet configrs --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - mongo-cluster

  shard1svr1:
    image: mongo:latest
    container_name: shard1svr1
    command: mongod --shardsvr --replSet shard1rs --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - mongo-cluster

  shard1svr2:
    image: mongo:latest
    container_name: shard1svr2
    command: mongod --shardsvr --replSet shard1rs --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - mongo-cluster

  shard1svr3:
    image: mongo:latest
    container_name: shard1svr3
    command: mongod --shardsvr --replSet shard1rs --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - mongo-cluster

  mongos1:
    image: mongo:latest
    container_name: mongos1
    command: mongos --configdb configrs/configsvr1:27017,configsvr2:27017,configsvr3:27017 --port 27017
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge
